# Generated by Django 4.0.5 on 2022-06-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author_name_book_dop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='DOP',
            field=models.IntegerField(default=0),
        ),
    ]
