# Generated by Django 4.0.5 on 2022-06-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_dop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='DOP',
        ),
        migrations.AddField(
            model_name='book',
            name='book_no',
            field=models.IntegerField(default=0),
        ),
    ]
